## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.random.randint(-5, 15, 20)
print(arr)
for i in range(arr.size):
    if (arr[i] > 3) & (arr[i] < 8):
        arr[i] = arr[i] * -1
print(arr)

[-3  8 10 -2  7  4  3  2 -2  8  0  4  1  0  2 13 12 -3 13 -2]
[-3  8 10 -2 -7 -4  3  2 -2  8  0 -4  1  0  2 13 12 -3 13 -2]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.random.randint(-10, 10, 20)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[  6   2   2   7  -5  -1  -8  -7  -7  -5   4  -8   0 -10  -9  -6   0  -8
  -1   3]
[  6   2   2   0  -5  -1  -8  -7  -7  -5   4  -8   0 -10  -9  -6   0  -8
  -1   3]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
arr = np.random.randint(-10, 10, (2, 3))
print(f'Origin array: \n{arr}')

grids = np.meshgrid(*arr)
result = np.column_stack([grid.ravel() for grid in grids])
print(f'Combinations: \n{result}')

Origin array: 
[[-10   8   9]
 [ -3   9   2]]
Combinations: 
[[-10  -3]
 [  8  -3]
 [  9  -3]
 [-10   9]
 [  8   9]
 [  9   9]
 [-10   2]
 [  8   2]
 [  9   2]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [148]:
first = np.random.randint(0, 5, (8,3))
second = np.random.randint(0, 5, (2,2))
print(f'First array: \n{first}')
print(f'Second array: \n{second}')

for s in second:
    us , cs = np.unique(s, return_counts=True)
    s_dict = dict(zip(us, cs))
    for f in first:
        uf , cf = np.unique(f, return_counts=True)
        f_dict = dict(zip(uf, cf))
        if all(f_dict.get(el, 0) >= s_dict[el] for el in s_dict):
            print(f'Row from first array with elements {s} from second array: {f}')

First array: 
[[1 3 3]
 [1 0 1]
 [0 0 1]
 [1 3 2]
 [2 1 1]
 [2 0 1]
 [1 0 3]
 [3 3 3]]
Second array: 
[[3 3]
 [1 3]]
Row from first array with elements [3 3] from second array: [1 3 3]
Row from first array with elements [3 3] from second array: [3 3 3]
Row from first array with elements [1 3] from second array: [1 3 3]
Row from first array with elements [1 3] from second array: [1 3 2]
Row from first array with elements [1 3] from second array: [1 0 3]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
matrix = np.random.randint(0, 3, (10,3))
print(f'Origin matrix(shape: {matrix.shape}): \n{matrix}')

mask = []
for row in matrix:
    if len(np.unique(row)) == 1:
        mask.append(False)
    else:
        mask.append(True)
        
new_matrix = matrix[mask]

print(print(f'New matrix(shape: {new_matrix.shape}): \n{new_matrix}'))

Origin matrix(shape: (10, 3)): 
[[0 2 1]
 [2 2 0]
 [0 1 0]
 [0 2 2]
 [1 0 1]
 [0 1 1]
 [2 0 2]
 [1 2 2]
 [2 1 1]
 [2 0 0]]
New matrix(shape: (10, 3)): 
[[0 2 1]
 [2 2 0]
 [0 1 0]
 [0 2 2]
 [1 0 1]
 [0 1 1]
 [2 0 2]
 [1 2 2]
 [2 1 1]
 [2 0 0]]
None


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
arr = np.random.randint(0, 2, (8, 4))
print(f'Origin array(shape: {arr.shape}): \n{arr}')

new_arr = np.unique(arr, axis = 0)
print(f'Array without duplicates(shape: {new_arr.shape}): \n{new_arr}')

Origin array(shape: (8, 4)): 
[[0 1 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 1 1]
 [0 0 1 1]
 [1 0 0 0]
 [0 1 1 0]
 [1 0 1 1]]
Array without duplicates(shape: (6, 4)): 
[[0 0 0 0]
 [0 0 1 1]
 [0 1 0 1]
 [0 1 1 0]
 [1 0 0 0]
 [1 0 1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
mult = 1
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
print(X)
for i in range(min(len(X[0]), len(X[1]))):
        if X[i][i] != 0:
            mult = mult * X[i][i]
print(f'Multiplication not-null diagonal elements: {mult}')

#numpy
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])  
print(X)
diag = X.diagonal()
mult = np.prod(diag[diag != 0])
print(f'Multiplication not-null diagonal elements: {mult}')

[[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
Multiplication not-null diagonal elements: 3
[[1 0 1]
 [2 0 2]
 [3 0 3]
 [4 4 4]]
Multiplication not-null diagonal elements: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [42]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(f'Is it the same multiset: {sorted(x) == sorted(y)}')

#numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
ux, cx = np.unique(x, return_counts = True)
uy, cy = np.unique(y, return_counts = True)
print(f'Is it the same multiset: {np.array_equal(ux, uy) and np.array_equal(cx, cy)}')

Is it the same multiset: True
Is it the same multiset: True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [64]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_el = None
for i in range(1, len(x)):
    if x[i-1] == 0 and (max_el == None or x[i] > max_el):
        max_el = x[i] 

if max_el == None:
    print('There are no elements after 0.')
else:
    print(f'Max element after 0: {max_el}')

#numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
indx = np.where(x == 0)[0] + 1
indx = indx[indx < len(x)]

if len(indx) == 0:
    print('There are no elements after 0.')
else:
    print(f'Max element after 0: {np.max(x[indx])}')

Max element after 0: 5
Max element after 0: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [104]:
x = [2, 2, 2, 3, 3, 3, 5]
numbers = []
freqs = []
counter = 1
for i in range(1, len(x)):      
    if (x[i-1] == x[i]):
        counter += 1;
    else:
        numbers.append(x[i-1])
        freqs.append(counter)
        counter = 1

numbers.append(x[-1])
freqs.append(counter)
print(numbers, freqs)
        
#numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
numbers = x[np.diff(x, prepend = 0) != 0]
freqs = np.diff(np.where(np.diff(x, prepend = 0))[0].tolist() + [len(x)])
print(numbers, freqs)

[2, 3, 5] [3, 3, 1]
[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [149]:
import scipy
import time
import math

X = [[1, 2], [0, 3], [1, 1]]
Y = [[2, 3], [3, 3], [0, 0]]
matrix = []

start = time.time()
for x in X:  
    row = []
    for y in Y:  
        dist = math.sqrt(sum((xi - yi) ** 2 for xi, yi in zip(x, y)))
        row.append(dist)
    matrix.append(row)
time.sleep(1) 
end = time.time()

print(f'Matrix of euclidean distances: \n{matrix}')
print(f'Runtime: {end - start:.4f} sec')

#scipy
start = time.time()
matrix = scipy.spatial.distance.cdist(X, Y, metric='euclidean')
time.sleep(1) 
end = time.time()

print(f'\nMatrix of euclidean distances: \n{matrix}')
print(f'Runtime: {end - start:.4f} sec')

#numpy
X = np.array([[1, 2], [0, 3], [1, 1]])
Y = np.array([[2, 3], [3, 3], [0, 0]])
matrix = np.zeros((len(X), len(Y)))

start = time.time()
for i, x in enumerate(X):  
    for j, y in enumerate(Y):  
        matrix[i, j] = np.linalg.norm(x - y)
time.sleep(1) 
end = time.time()

print(f'\nMatrix of euclidean distances: \n{matrix}')
print(f'Runtime: {end - start:.4f} sec')

Matrix of euclidean distances: 
[[1.4142135623730951, 2.23606797749979, 2.23606797749979], [2.0, 3.0, 3.0], [2.23606797749979, 2.8284271247461903, 1.4142135623730951]]
Runtime: 1.0065 sec

Matrix of euclidean distances: 
[[1.41421356 2.23606798 2.23606798]
 [2.         3.         3.        ]
 [2.23606798 2.82842712 1.41421356]]
Runtime: 1.0016 sec

Matrix of euclidean distances: 
[[1.41421356 2.23606798 2.23606798]
 [2.         3.         3.        ]
 [2.23606798 2.82842712 1.41421356]]
Runtime: 1.0038 sec


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [15]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [16]:
average_calories = np.mean(calorie_stats)
(f'Average score for calories {average_calories:.2f}. It\'s greater than CrunchieMunchies by {average_calories - 60:.2f} calories')

"Average score for calories 106.88. It's greater than CrunchieMunchies by 46.88 calories"

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [17]:
calorie_stats_sorted = np.sort(calorie_stats)
print(f'Sorted calories of competitors:\n{calorie_stats_sorted}')

Sorted calories of competitors:
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [18]:
median_calories = np.median(calorie_stats)
print(f'Median score for calories: {median_calories}')

Median score for calories: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [24]:
nth_percentile = 0
for i in range(1, 101):
    perc = np.percentile(calorie_stats, i)
    if perc > 60:
        nth_percentile = i
        break
print(f'Min percentile greater than 60: {nth_percentile}')
        

Min percentile greater than 60: 4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [28]:
more_calories = calorie_stats[calorie_stats > 60].size * 100 / calorie_stats.size
print(f'Percent of competitors with more than 60 calories per portion: {more_calories:.2f}%')

Percent of competitors with more than 60 calories per portion: 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [34]:
calorie_std = np.std(calorie_stats)
print(f'Standard deviation of calories: {calorie_std:.2f}')
#С помощью отклонения можно глянуть диапазон основной доли данных(среднее +- отклонение), и тогда опять же будет 
#видно, что основная часть конкурентов сильно уступает по калорийности.

Standard deviation of calories: 19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
#Исходя из проделанной работы, можно сделать вывод, что наиболее информативными метриками для аналитика будут медиана, 
#процентили и стандартное отклонение. Согласно им данные хлопья выигрывают по калорийности, что привлечет потребителей,
#котролирующих свое питание. Статистики можно использовать в рекламной кампания для привлечения новых клиентов.